"""
Django settings for carona project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# settings.py (trecho inicial) — cole no topo do arquivo
import os
from pathlib import Path
from dotenv import load_dotenv


# ===== STATICFILES (necessário para funcionar no Docker Hub) =====
STATIC_URL = '/static/'
STATIC_ROOT = Path(__file__).resolve().parent.parent / "staticfiles"
STATICFILES_DIRS = [ Path(__file__).resolve().parent.parent / "static" ]


# Retenção do sistema em depósitos (%)
PORCENTAGEM_RETENCAO = 0.12  # 12%

# caminho base do projeto
BASE_DIR = Path(__file__).resolve().parent.parent

# carrega o arquivo .env na raiz do projeto (BASE_DIR)
ENV_PATH = BASE_DIR / ".env"
if ENV_PATH.exists():
    load_dotenv(dotenv_path=ENV_PATH)


# --- ABACATEPAY ---
# settings.py
ABACATEPAY_WEBHOOK_SECRET = "babuinosbobocasbalbiciandoembandohpgrifinoria"
ABACATEPAY_PUBLIC_KEY = "t9dXRhHHo3yDEj5pVDYz0frf7q6bMKyMRmxxCPIPp3RCplBfXRxqlC6ZpiWmOqj4L63qEaeUOtrCI8P0VMUgo6iIga2ri9ogaHFs0WIIywSMg0q7RmBfybe1E5XJcfC4IW3alNqym0tXoAKkzvfEjZxV6bE0oG2zJrNNYmUCKZyV0KZ3JS8Votf9EAWWYdiDkMkpbMdPggfh1EqHlVkMiTady6jOR3hyzGEHrIz2Ret0xHKMbiqkr9HS1JhNHDX9"

ABACATEPAY_BASE_URL = os.getenv("ABACATEPAY_BASE_URL", "https://api.abacatepay.com/v1")
ABACATEPAY_API_KEY = os.getenv("ABACATEPAY_API_KEY", "")
ABACATEPAY_TIMEOUT = int(os.getenv("ABACATEPAY_TIMEOUT", 30))
ABACATEPAY_RETRIES = int(os.getenv("ABACATEPAY_RETRIES", 2))


# URLs de redirecionamento padrão para pagamentos
ABACATEPAY_RETURN_URL = os.getenv(
    "ABACATEPAY_RETURN_URL", "https://127.0.0.1:8000/pagamentos/retorno/"
)
ABACATEPAY_COMPLETION_URL = os.getenv(
    "ABACATEPAY_COMPLETION_URL", "https://127.0.0.1:8000/pagamentos/concluido/"
)

# --- URL base da aplicação ---
SITE_BASE_URL = os.getenv("SITE_BASE_URL", "http://127.0.0.1:8000")


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-&twz63=3149t^-1)6(p^a47oev391yc(w&o_pysxx@dqmaymto'
DEBUG = True
ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'passageiros',
    'pagamentos',
    'corrida',
    'notificacao', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # ===== ADICIONADO — necessário para servir CSS no Docker =====
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'carona.urls'
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'carona.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]


LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [ os.path.join(BASE_DIR, 'static') ]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'usuarios.Usuario'  
LOGIN_URL = 'usuarios:login'
LOGIN_REDIRECT_URL = 'usuarios:pagina_inicial'
LOGOUT_REDIRECT_URL = 'usuarios:login'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

ORS_API_KEY = 'eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjlmZjcxZGFiMTFiYjQ5MGQ5MDczOWI2MjBjYTA0MzUzIiwiaCI6Im11cm11cjY0In0='
